services:
  db:
    image: postgres:latest
    container_name: inventory-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: inventory
    ports:
      - "5432:5432"
